/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_opencv_ImgCorrectTilt */

#ifndef _Included_test_opencv_ImgCorrectTilt
#define _Included_test_opencv_ImgCorrectTilt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_opencv_ImgCorrectTilt
 * Method:    correct
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_test_opencv_ImgCorrectTilt_correct
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
